/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

'use strict';
import * as models from './models';

export interface IdentityProviderAttribute {


    /**
     * OpenId Connect or SAML2 attribute name
     */
    attributeName?: IdentityProviderAttribute.AttributeNameEnum;

    /**
     * OpenId Connect or SAML2 attribute value
     */
    attributeValue?: string;

    createdAt?: Date;

    updatedAt?: Date;
}
export namespace IdentityProviderAttribute {

    export enum AttributeNameEnum {
        importUrl = <any> 'importUrl',
        validateSignature = <any> 'validateSignature',
        signingCertificate = <any> 'signingCertificate',
        singleLogoutServiceUrl = <any> 'singleLogoutServiceUrl',
        postBindingResponse = <any> 'postBindingResponse',
        postBindingAuthnRequest = <any> 'postBindingAuthnRequest',
        singleSignOnServiceUrl = <any> 'singleSignOnServiceUrl',
        wantAuthnRequestsSigned = <any> 'wantAuthnRequestsSigned',
        userInfoUrl = <any> 'userInfoUrl',
        tokenUrl = <any> 'tokenUrl',
        authorizationUrl = <any> 'authorizationUrl',
        logoutUrl = <any> 'logoutUrl',
        issuer = <any> 'issuer',
        publicKeySignatureVerifier = <any> 'publicKeySignatureVerifier',
        clientId = <any> 'clientId',
        clientSecret = <any> 'clientSecret',
    }
}
