/**
 * Maritime Cloud Identity Registry API
 * Maritime Cloud Identity Registry API can be used for managing entities in the Maritime Cloud.
 *
 * OpenAPI spec version: 0.0.1
 * Contact: info@maritimecloud.net
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface Organization {
    address: string;

    /**
     * Cannot be created/updated by editing in the model. Use the dedicate create and revoke calls.
     */
    certificates?: Array<models.Certificate>;

    country: string;

    createdAt?: Date;

    email: string;

    /**
     * Type of identity federation used by organization
     */
    federationType?: Organization.FederationTypeEnum;

    identityProviderAttributes?: Array<models.IdentityProviderAttribute>;

    /**
     * The Maritime Resource Name
     */
    mrn: string;

    /**
     * The name of the organization
     */
    name: string;

    updatedAt?: Date;

    url: string;

}
export namespace Organization {
    export enum FederationTypeEnum {
        TestIdp = <any> 'test-idp',
        OwnIdp = <any> 'own-idp',
        ExternalIdp = <any> 'external-idp'
    }
}
