export const MC_ADMIN = 'MCADMIN';
export const DONT_OVERWRITE_CONTENT_TYPE = 'DONT_OVERWRITE_CONTENT_TYPE';
export const SHOW_ENDORSEMENTS = true;
export const MAX_HTTP_LOG_ENTRIES = 5;
export const PAGE_SIZE_DEFAULT = 300;
