export * from './CertificatecontrollerApi';
import { CertificatecontrollerApi } from './CertificatecontrollerApi';
export * from './DevicecontrollerApi';
import { DevicecontrollerApi } from './DevicecontrollerApi';
export * from './LogocontrollerApi';
import { LogocontrollerApi } from './LogocontrollerApi';
export * from './OrganizationcontrollerApi';
import { OrganizationcontrollerApi } from './OrganizationcontrollerApi';
export * from './RolecontrollerApi';
import { RolecontrollerApi } from './RolecontrollerApi';
export * from './ServicecontrollerApi';
import { ServicecontrollerApi } from './ServicecontrollerApi';
export * from './UsercontrollerApi';
import { UsercontrollerApi } from './UsercontrollerApi';
export * from './VesselcontrollerApi';
import { VesselcontrollerApi } from './VesselcontrollerApi';
export const APIS = [CertificatecontrollerApi, DevicecontrollerApi, LogocontrollerApi, OrganizationcontrollerApi, RolecontrollerApi, ServicecontrollerApi, UsercontrollerApi, VesselcontrollerApi];
