/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import {Http, Headers, RequestOptionsArgs, Response, URLSearchParams} from '@angular/http';
import {Injectable, Optional} from '@angular/core';
import {Observable} from 'rxjs/Observable';
import * as models from '../model/models';
import 'rxjs/Rx';

/* tslint:disable:no-unused-variable member-ordering */

'use strict';

@Injectable()
export class LogocontrollerApi {
    protected basePath = 'https://api.maritimecloud.net:443/';
    public defaultHeaders : Headers = new Headers();

    constructor(protected http: Http, @Optional() basePath: string) {
        if (basePath) {
            this.basePath = basePath;
        }
    }

    /**
     * createLogoPost
     *
     * @param orgShortName orgShortName
     * @param logo logo
     */
    public createLogoPostUsingPOST (orgShortName: string, logo: any, extraHttpRequestParams?: any ) : Observable<any> {
        const path = this.basePath + '/oidc/api/org/{orgShortName}/logo'
            .replace('{' + 'orgShortName' + '}', String(orgShortName));

        let queryParameters = new URLSearchParams();
        let headerParams = this.defaultHeaders;
        let formParams = new URLSearchParams();

        // verify required parameter 'orgShortName' is not null or undefined
        if (orgShortName === null || orgShortName === undefined) {
            throw new Error('Required parameter orgShortName was null or undefined when calling createLogoPostUsingPOST.');
        }
        // verify required parameter 'logo' is not null or undefined
        if (logo === null || logo === undefined) {
            throw new Error('Required parameter logo was null or undefined when calling createLogoPostUsingPOST.');
        }
        headerParams.set('Content-Type', 'application/x-www-form-urlencoded');

        formParams['logo'] = logo;

        let requestOptions: RequestOptionsArgs = {
            method: 'POST',
            headers: headerParams,
            search: queryParameters
        };
        requestOptions.body = formParams.toString();

        return this.http.request(path, requestOptions)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json();
                }
            });
    }

    /**
     * createLogoPost
     *
     * @param orgShortName orgShortName
     * @param logo logo
     */
    public createLogoPostUsingPOST1 (orgShortName: string, logo: any, extraHttpRequestParams?: any ) : Observable<any> {
        const path = this.basePath + '/x509/api/org/{orgShortName}/logo'
            .replace('{' + 'orgShortName' + '}', String(orgShortName));

        let queryParameters = new URLSearchParams();
        let headerParams = this.defaultHeaders;
        let formParams = new URLSearchParams();

        // verify required parameter 'orgShortName' is not null or undefined
        if (orgShortName === null || orgShortName === undefined) {
            throw new Error('Required parameter orgShortName was null or undefined when calling createLogoPostUsingPOST1.');
        }
        // verify required parameter 'logo' is not null or undefined
        if (logo === null || logo === undefined) {
            throw new Error('Required parameter logo was null or undefined when calling createLogoPostUsingPOST1.');
        }
        headerParams.set('Content-Type', 'application/x-www-form-urlencoded');

        formParams['logo'] = logo;

        let requestOptions: RequestOptionsArgs = {
            method: 'POST',
            headers: headerParams,
            search: queryParameters
        };
        requestOptions.body = formParams.toString();

        return this.http.request(path, requestOptions)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json();
                }
            });
    }

    /**
     * createLogoPut
     *
     * @param orgShortName orgShortName
     * @param logo logo
     */
    public createLogoPutUsingPUT (orgShortName: string, logo: Array<string>, extraHttpRequestParams?: any ) : Observable<any> {
        const path = this.basePath + '/oidc/api/org/{orgShortName}/logo'
            .replace('{' + 'orgShortName' + '}', String(orgShortName));

        let queryParameters = new URLSearchParams();
        let headerParams = this.defaultHeaders;
        // verify required parameter 'orgShortName' is not null or undefined
        if (orgShortName === null || orgShortName === undefined) {
            throw new Error('Required parameter orgShortName was null or undefined when calling createLogoPutUsingPUT.');
        }
        // verify required parameter 'logo' is not null or undefined
        if (logo === null || logo === undefined) {
            throw new Error('Required parameter logo was null or undefined when calling createLogoPutUsingPUT.');
        }
        let requestOptions: RequestOptionsArgs = {
            method: 'PUT',
            headers: headerParams,
            search: queryParameters
        };
        requestOptions.body = JSON.stringify(logo);

        return this.http.request(path, requestOptions)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json();
                }
            });
    }

    /**
     * createLogoPut
     *
     * @param orgShortName orgShortName
     * @param logo logo
     */
    public createLogoPutUsingPUT1 (orgShortName: string, logo: Array<string>, extraHttpRequestParams?: any ) : Observable<any> {
        const path = this.basePath + '/x509/api/org/{orgShortName}/logo'
            .replace('{' + 'orgShortName' + '}', String(orgShortName));

        let queryParameters = new URLSearchParams();
        let headerParams = this.defaultHeaders;
        // verify required parameter 'orgShortName' is not null or undefined
        if (orgShortName === null || orgShortName === undefined) {
            throw new Error('Required parameter orgShortName was null or undefined when calling createLogoPutUsingPUT1.');
        }
        // verify required parameter 'logo' is not null or undefined
        if (logo === null || logo === undefined) {
            throw new Error('Required parameter logo was null or undefined when calling createLogoPutUsingPUT1.');
        }
        let requestOptions: RequestOptionsArgs = {
            method: 'PUT',
            headers: headerParams,
            search: queryParameters
        };
        requestOptions.body = JSON.stringify(logo);

        return this.http.request(path, requestOptions)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json();
                }
            });
    }

    /**
     * deleteLogo
     *
     * @param orgShortName orgShortName
     */
    public deleteLogoUsingDELETE (orgShortName: string, extraHttpRequestParams?: any ) : Observable<any> {
        const path = this.basePath + '/oidc/api/org/{orgShortName}/logo'
            .replace('{' + 'orgShortName' + '}', String(orgShortName));

        let queryParameters = new URLSearchParams();
        let headerParams = this.defaultHeaders;
        // verify required parameter 'orgShortName' is not null or undefined
        if (orgShortName === null || orgShortName === undefined) {
            throw new Error('Required parameter orgShortName was null or undefined when calling deleteLogoUsingDELETE.');
        }
        let requestOptions: RequestOptionsArgs = {
            method: 'DELETE',
            headers: headerParams,
            search: queryParameters
        };

        return this.http.request(path, requestOptions)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json();
                }
            });
    }

    /**
     * deleteLogo
     *
     * @param orgShortName orgShortName
     */
    public deleteLogoUsingDELETE1 (orgShortName: string, extraHttpRequestParams?: any ) : Observable<any> {
        const path = this.basePath + '/x509/api/org/{orgShortName}/logo'
            .replace('{' + 'orgShortName' + '}', String(orgShortName));

        let queryParameters = new URLSearchParams();
        let headerParams = this.defaultHeaders;
        // verify required parameter 'orgShortName' is not null or undefined
        if (orgShortName === null || orgShortName === undefined) {
            throw new Error('Required parameter orgShortName was null or undefined when calling deleteLogoUsingDELETE1.');
        }
        let requestOptions: RequestOptionsArgs = {
            method: 'DELETE',
            headers: headerParams,
            search: queryParameters
        };

        return this.http.request(path, requestOptions)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json();
                }
            });
    }

    /**
     * getLogo
     *
     * @param orgShortName orgShortName
     */
    public getLogoUsingGET (orgShortName: string, extraHttpRequestParams?: any ) : Observable<any> {
        const path = this.basePath + '/oidc/api/org/{orgShortName}/logo'
            .replace('{' + 'orgShortName' + '}', String(orgShortName));

        let queryParameters = new URLSearchParams();
        let headerParams = this.defaultHeaders;
        // verify required parameter 'orgShortName' is not null or undefined
        if (orgShortName === null || orgShortName === undefined) {
            throw new Error('Required parameter orgShortName was null or undefined when calling getLogoUsingGET.');
        }
        let requestOptions: RequestOptionsArgs = {
            method: 'GET',
            headers: headerParams,
            search: queryParameters
        };

        return this.http.request(path, requestOptions)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json();
                }
            });
    }

    /**
     * getLogo
     *
     * @param orgShortName orgShortName
     */
    public getLogoUsingGET1 (orgShortName: string, extraHttpRequestParams?: any ) : Observable<any> {
        const path = this.basePath + '/x509/api/org/{orgShortName}/logo'
            .replace('{' + 'orgShortName' + '}', String(orgShortName));

        let queryParameters = new URLSearchParams();
        let headerParams = this.defaultHeaders;
        // verify required parameter 'orgShortName' is not null or undefined
        if (orgShortName === null || orgShortName === undefined) {
            throw new Error('Required parameter orgShortName was null or undefined when calling getLogoUsingGET1.');
        }
        let requestOptions: RequestOptionsArgs = {
            method: 'GET',
            headers: headerParams,
            search: queryParameters
        };

        return this.http.request(path, requestOptions)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json();
                }
            });
    }

}
