// NOTE: be carefull when autogenerating. This file is changed manually
/**
 * Maritime Connectivity Platform Identity Registry API
 * MCP Identity Registry API can be used for managing entities in the Maritime Connectivity Platform.
 *
 * OpenAPI spec version: 0.7.0
 * Contact: info@maritimecloud.net
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { Http, Headers, URLSearchParams }                    from '@angular/http';
import { RequestMethod, RequestOptions, RequestOptionsArgs } from '@angular/http';
import { Response, ResponseContentType }                     from '@angular/http';

import { Observable }                                        from 'rxjs/Observable';
import 'rxjs/add/operator/map';

import * as models                                           from '../model/models';
import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class ServicecontrollerApi {

    protected basePath = 'https://test-api.maritimecloud.net';
    public defaultHeaders: Headers = new Headers();
    public configuration: Configuration = new Configuration();

    constructor(protected http: Http, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
        }
    }

    /**
     * 
     * @summary createService
     * @param orgMrn orgMrn
     * @param input input
     */
    public createServiceUsingPOST(orgMrn: string, input: models.Service, extraHttpRequestParams?: any): Observable<models.Service> {
        return this.createServiceUsingPOSTWithHttpInfo(orgMrn, input, extraHttpRequestParams)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json() || {};
                }
            });
    }

    /**
     * 
     * @summary createService
     * @param orgMrn orgMrn
     * @param input input
     */
    public createServiceUsingPOST1(orgMrn: string, input: models.Service, extraHttpRequestParams?: any): Observable<models.Service> {
        return this.createServiceUsingPOST1WithHttpInfo(orgMrn, input, extraHttpRequestParams)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json() || {};
                }
            });
    }

    /**
     * 
     * @summary deleteService
     * @param orgMrn orgMrn
     * @param serviceMrn serviceMrn
     * @param version version
     */
    public deleteServiceUsingDELETE(orgMrn: string, serviceMrn: string, version: string, extraHttpRequestParams?: any): Observable<any> {
        return this.deleteServiceUsingDELETEWithHttpInfo(orgMrn, serviceMrn, version, extraHttpRequestParams)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json() || {};
                }
            });
    }

    /**
     * 
     * @summary deleteService
     * @param orgMrn orgMrn
     * @param serviceMrn serviceMrn
     * @param version version
     */
    public deleteServiceUsingDELETE1(orgMrn: string, serviceMrn: string, version: string, extraHttpRequestParams?: any): Observable<any> {
        return this.deleteServiceUsingDELETE1WithHttpInfo(orgMrn, serviceMrn, version, extraHttpRequestParams)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json() || {};
                }
            });
    }

    /**
     * 
     * @summary getOrganizationServices
     * @param orgMrn orgMrn
     * @param page Results page you want to retrieve (0..N)
     * @param size Number of records per page
     * @param sort Sorting criteria in the format: property(,asc|desc). Default sort order is ascending. Multiple sort criteria are supported.
     */
    public getOrganizationServicesUsingGET(orgMrn: string, page?: number, size?: number, sort?: Array<string>, extraHttpRequestParams?: any): Observable<models.PageService> {
        return this.getOrganizationServicesUsingGETWithHttpInfo(orgMrn, page, size, sort, extraHttpRequestParams)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json() || {};
                }
            });
    }

    /**
     * 
     * @summary getOrganizationServices
     * @param orgMrn orgMrn
     * @param page Results page you want to retrieve (0..N)
     * @param size Number of records per page
     * @param sort Sorting criteria in the format: property(,asc|desc). Default sort order is ascending. Multiple sort criteria are supported.
     */
    public getOrganizationServicesUsingGET1(orgMrn: string, page?: number, size?: number, sort?: Array<string>, extraHttpRequestParams?: any): Observable<models.PageService> {
        return this.getOrganizationServicesUsingGET1WithHttpInfo(orgMrn, page, size, sort, extraHttpRequestParams)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json() || {};
                }
            });
    }

    /**
     * 
     * @summary getServiceJbossXml
     * @param orgMrn orgMrn
     * @param serviceMrn serviceMrn
     * @param version version
     */
    public getServiceJbossXmlUsingGET(orgMrn: string, serviceMrn: string, version: string, extraHttpRequestParams?: any): Observable<string> {
        return this.getServiceJbossXmlUsingGETWithHttpInfo(orgMrn, serviceMrn, version, extraHttpRequestParams)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
	                // NOTE: be carefull when autogenerating. This file is changed manually
	                return response.text();
                }
            });
    }

    /**
     * 
     * @summary getServiceJbossXml
     * @param orgMrn orgMrn
     * @param serviceMrn serviceMrn
     * @param version version
     */
    public getServiceJbossXmlUsingGET1(orgMrn: string, serviceMrn: string, version: string, extraHttpRequestParams?: any): Observable<string> {
        return this.getServiceJbossXmlUsingGET1WithHttpInfo(orgMrn, serviceMrn, version, extraHttpRequestParams)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json() || {};
                }
            });
    }

    /**
     * 
     * @summary getServiceKeycloakJson
     * @param orgMrn orgMrn
     * @param serviceMrn serviceMrn
     * @param version version
     */
    public getServiceKeycloakJsonUsingGET(orgMrn: string, serviceMrn: string, version: string, extraHttpRequestParams?: any): Observable<string> {
        return this.getServiceKeycloakJsonUsingGETWithHttpInfo(orgMrn, serviceMrn, version, extraHttpRequestParams)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
	                // NOTE: be carefull when autogenerating. This file is changed manually
	                return response.text();
                }
            });
    }

    /**
     * 
     * @summary getServiceKeycloakJson
     * @param orgMrn orgMrn
     * @param serviceMrn serviceMrn
     * @param version version
     */
    public getServiceKeycloakJsonUsingGET1(orgMrn: string, serviceMrn: string, version: string, extraHttpRequestParams?: any): Observable<string> {
        return this.getServiceKeycloakJsonUsingGET1WithHttpInfo(orgMrn, serviceMrn, version, extraHttpRequestParams)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json() || {};
                }
            });
    }

    /**
     * 
     * @summary getService
     * @param orgMrn orgMrn
     * @param serviceMrn serviceMrn
     * @param page Results page you want to retrieve (0..N)
     * @param size Number of records per page
     * @param sort Sorting criteria in the format: property(,asc|desc). Default sort order is ascending. Multiple sort criteria are supported.
     */
    public getServiceUsingGET(orgMrn: string, serviceMrn: string, page?: number, size?: number, sort?: Array<string>, extraHttpRequestParams?: any): Observable<models.PageService> {
        return this.getServiceUsingGETWithHttpInfo(orgMrn, serviceMrn, page, size, sort, extraHttpRequestParams)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json() || {};
                }
            });
    }

    /**
     * 
     * @summary getService
     * @param orgMrn orgMrn
     * @param serviceMrn serviceMrn
     * @param page Results page you want to retrieve (0..N)
     * @param size Number of records per page
     * @param sort Sorting criteria in the format: property(,asc|desc). Default sort order is ascending. Multiple sort criteria are supported.
     */
    public getServiceUsingGET1(orgMrn: string, serviceMrn: string, page?: number, size?: number, sort?: Array<string>, extraHttpRequestParams?: any): Observable<models.PageService> {
        return this.getServiceUsingGET1WithHttpInfo(orgMrn, serviceMrn, page, size, sort, extraHttpRequestParams)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json() || {};
                }
            });
    }

    /**
     * 
     * @summary getServiceVersion
     * @param orgMrn orgMrn
     * @param serviceMrn serviceMrn
     * @param version version
     */
    public getServiceVersionUsingGET(orgMrn: string, serviceMrn: string, version: string, extraHttpRequestParams?: any): Observable<models.Service> {
        return this.getServiceVersionUsingGETWithHttpInfo(orgMrn, serviceMrn, version, extraHttpRequestParams)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json() || {};
                }
            });
    }

    /**
     * 
     * @summary getServiceVersion
     * @param orgMrn orgMrn
     * @param serviceMrn serviceMrn
     * @param version version
     */
    public getServiceVersionUsingGET1(orgMrn: string, serviceMrn: string, version: string, extraHttpRequestParams?: any): Observable<models.Service> {
        return this.getServiceVersionUsingGET1WithHttpInfo(orgMrn, serviceMrn, version, extraHttpRequestParams)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json() || {};
                }
            });
    }

    /**
     * 
     * @summary newServiceCert
     * @param orgMrn orgMrn
     * @param serviceMrn serviceMrn
     * @param version version
     */
    public newServiceCertUsingGET(orgMrn: string, serviceMrn: string, version: string, extraHttpRequestParams?: any): Observable<models.CertificateBundle> {
        return this.newServiceCertUsingGETWithHttpInfo(orgMrn, serviceMrn, version, extraHttpRequestParams)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json() || {};
                }
            });
    }

    /**
     * 
     * @summary newServiceCert
     * @param orgMrn orgMrn
     * @param serviceMrn serviceMrn
     * @param version version
     */
    public newServiceCertUsingGET1(orgMrn: string, serviceMrn: string, version: string, extraHttpRequestParams?: any): Observable<models.CertificateBundle> {
        return this.newServiceCertUsingGET1WithHttpInfo(orgMrn, serviceMrn, version, extraHttpRequestParams)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json() || {};
                }
            });
    }

    /**
     * 
     * @summary revokeServiceCert
     * @param orgMrn orgMrn
     * @param serviceMrn serviceMrn
     * @param version version
     * @param certId certId
     * @param input input
     */
    public revokeServiceCertUsingPOST(orgMrn: string, serviceMrn: string, version: string, certId: string, input: models.CertificateRevocation, extraHttpRequestParams?: any): Observable<any> {
        return this.revokeServiceCertUsingPOSTWithHttpInfo(orgMrn, serviceMrn, version, certId, input, extraHttpRequestParams)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json() || {};
                }
            });
    }

    /**
     * 
     * @summary revokeServiceCert
     * @param orgMrn orgMrn
     * @param serviceMrn serviceMrn
     * @param version version
     * @param certId certId
     * @param input input
     */
    public revokeServiceCertUsingPOST1(orgMrn: string, serviceMrn: string, version: string, certId: string, input: models.CertificateRevocation, extraHttpRequestParams?: any): Observable<any> {
        return this.revokeServiceCertUsingPOST1WithHttpInfo(orgMrn, serviceMrn, version, certId, input, extraHttpRequestParams)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json() || {};
                }
            });
    }

    /**
     * 
     * @summary updateService
     * @param orgMrn orgMrn
     * @param serviceMrn serviceMrn
     * @param version version
     * @param input input
     */
    public updateServiceUsingPUT(orgMrn: string, serviceMrn: string, version: string, input: models.Service, extraHttpRequestParams?: any): Observable<any> {
        return this.updateServiceUsingPUTWithHttpInfo(orgMrn, serviceMrn, version, input, extraHttpRequestParams)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json() || {};
                }
            });
    }

    /**
     * 
     * @summary updateService
     * @param orgMrn orgMrn
     * @param serviceMrn serviceMrn
     * @param version version
     * @param input input
     */
    public updateServiceUsingPUT1(orgMrn: string, serviceMrn: string, version: string, input: models.Service, extraHttpRequestParams?: any): Observable<any> {
        return this.updateServiceUsingPUT1WithHttpInfo(orgMrn, serviceMrn, version, input, extraHttpRequestParams)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json() || {};
                }
            });
    }


    /**
     * createService
     * 
     * @param orgMrn orgMrn
     * @param input input
     */
    public createServiceUsingPOSTWithHttpInfo(orgMrn: string, input: models.Service, extraHttpRequestParams?: any): Observable<Response> {
        const path = this.basePath + '/oidc/api/org/${orgMrn}/service'
                    .replace('${' + 'orgMrn' + '}', String(orgMrn));

        let queryParameters = new URLSearchParams();
        let headers = new Headers(this.defaultHeaders.toJSON()); // https://github.com/angular/angular/issues/6845
        // verify required parameter 'orgMrn' is not null or undefined
        if (orgMrn === null || orgMrn === undefined) {
            throw new Error('Required parameter orgMrn was null or undefined when calling createServiceUsingPOST.');
        }
        // verify required parameter 'input' is not null or undefined
        if (input === null || input === undefined) {
            throw new Error('Required parameter input was null or undefined when calling createServiceUsingPOST.');
        }
        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json'
        ];

        // to determine the Accept header
        let produces: string[] = [
            'application/json;charset=UTF-8'
        ];

        headers.set('Content-Type', 'application/json');

        let requestOptions: RequestOptionsArgs = new RequestOptions({
            method: RequestMethod.Post,
            headers: headers,
            body: input == null ? '' : JSON.stringify(input), // https://github.com/angular/angular/issues/10612
            search: queryParameters,
            withCredentials:this.configuration.withCredentials
        });
        // https://github.com/swagger-api/swagger-codegen/issues/4037
        if (extraHttpRequestParams) {
            requestOptions = (<any>Object).assign(requestOptions, extraHttpRequestParams);
        }

        return this.http.request(path, requestOptions);
    }

    /**
     * createService
     * 
     * @param orgMrn orgMrn
     * @param input input
     */
    public createServiceUsingPOST1WithHttpInfo(orgMrn: string, input: models.Service, extraHttpRequestParams?: any): Observable<Response> {
        const path = this.basePath + '/x509/api/org/${orgMrn}/service'
                    .replace('${' + 'orgMrn' + '}', String(orgMrn));

        let queryParameters = new URLSearchParams();
        let headers = new Headers(this.defaultHeaders.toJSON()); // https://github.com/angular/angular/issues/6845
        // verify required parameter 'orgMrn' is not null or undefined
        if (orgMrn === null || orgMrn === undefined) {
            throw new Error('Required parameter orgMrn was null or undefined when calling createServiceUsingPOST1.');
        }
        // verify required parameter 'input' is not null or undefined
        if (input === null || input === undefined) {
            throw new Error('Required parameter input was null or undefined when calling createServiceUsingPOST1.');
        }
        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json'
        ];

        // to determine the Accept header
        let produces: string[] = [
            'application/json;charset=UTF-8'
        ];

        headers.set('Content-Type', 'application/json');

        let requestOptions: RequestOptionsArgs = new RequestOptions({
            method: RequestMethod.Post,
            headers: headers,
            body: input == null ? '' : JSON.stringify(input), // https://github.com/angular/angular/issues/10612
            search: queryParameters,
            withCredentials:this.configuration.withCredentials
        });
        // https://github.com/swagger-api/swagger-codegen/issues/4037
        if (extraHttpRequestParams) {
            requestOptions = (<any>Object).assign(requestOptions, extraHttpRequestParams);
        }

        return this.http.request(path, requestOptions);
    }

    /**
     * deleteService
     * 
     * @param orgMrn orgMrn
     * @param serviceMrn serviceMrn
     * @param version version
     */
    public deleteServiceUsingDELETEWithHttpInfo(orgMrn: string, serviceMrn: string, version: string, extraHttpRequestParams?: any): Observable<Response> {
        const path = this.basePath + '/oidc/api/org/${orgMrn}/service/${serviceMrn}/${version}'
                    .replace('${' + 'orgMrn' + '}', String(orgMrn))
                    .replace('${' + 'serviceMrn' + '}', String(serviceMrn))
                    .replace('${' + 'version' + '}', String(version));

        let queryParameters = new URLSearchParams();
        let headers = new Headers(this.defaultHeaders.toJSON()); // https://github.com/angular/angular/issues/6845
        // verify required parameter 'orgMrn' is not null or undefined
        if (orgMrn === null || orgMrn === undefined) {
            throw new Error('Required parameter orgMrn was null or undefined when calling deleteServiceUsingDELETE.');
        }
        // verify required parameter 'serviceMrn' is not null or undefined
        if (serviceMrn === null || serviceMrn === undefined) {
            throw new Error('Required parameter serviceMrn was null or undefined when calling deleteServiceUsingDELETE.');
        }
        // verify required parameter 'version' is not null or undefined
        if (version === null || version === undefined) {
            throw new Error('Required parameter version was null or undefined when calling deleteServiceUsingDELETE.');
        }
        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json'
        ];

        // to determine the Accept header
        let produces: string[] = [
            '*/*'
        ];

        let requestOptions: RequestOptionsArgs = new RequestOptions({
            method: RequestMethod.Delete,
            headers: headers,
            search: queryParameters,
            withCredentials:this.configuration.withCredentials
        });
        // https://github.com/swagger-api/swagger-codegen/issues/4037
        if (extraHttpRequestParams) {
            requestOptions = (<any>Object).assign(requestOptions, extraHttpRequestParams);
        }

        return this.http.request(path, requestOptions);
    }

    /**
     * deleteService
     * 
     * @param orgMrn orgMrn
     * @param serviceMrn serviceMrn
     * @param version version
     */
    public deleteServiceUsingDELETE1WithHttpInfo(orgMrn: string, serviceMrn: string, version: string, extraHttpRequestParams?: any): Observable<Response> {
        const path = this.basePath + '/x509/api/org/${orgMrn}/service/${serviceMrn}/${version}'
                    .replace('${' + 'orgMrn' + '}', String(orgMrn))
                    .replace('${' + 'serviceMrn' + '}', String(serviceMrn))
                    .replace('${' + 'version' + '}', String(version));

        let queryParameters = new URLSearchParams();
        let headers = new Headers(this.defaultHeaders.toJSON()); // https://github.com/angular/angular/issues/6845
        // verify required parameter 'orgMrn' is not null or undefined
        if (orgMrn === null || orgMrn === undefined) {
            throw new Error('Required parameter orgMrn was null or undefined when calling deleteServiceUsingDELETE1.');
        }
        // verify required parameter 'serviceMrn' is not null or undefined
        if (serviceMrn === null || serviceMrn === undefined) {
            throw new Error('Required parameter serviceMrn was null or undefined when calling deleteServiceUsingDELETE1.');
        }
        // verify required parameter 'version' is not null or undefined
        if (version === null || version === undefined) {
            throw new Error('Required parameter version was null or undefined when calling deleteServiceUsingDELETE1.');
        }
        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json'
        ];

        // to determine the Accept header
        let produces: string[] = [
            '*/*'
        ];

        let requestOptions: RequestOptionsArgs = new RequestOptions({
            method: RequestMethod.Delete,
            headers: headers,
            search: queryParameters,
            withCredentials:this.configuration.withCredentials
        });
        // https://github.com/swagger-api/swagger-codegen/issues/4037
        if (extraHttpRequestParams) {
            requestOptions = (<any>Object).assign(requestOptions, extraHttpRequestParams);
        }

        return this.http.request(path, requestOptions);
    }

    /**
     * getOrganizationServices
     * 
     * @param orgMrn orgMrn
     * @param page Results page you want to retrieve (0..N)
     * @param size Number of records per page
     * @param sort Sorting criteria in the format: property(,asc|desc). Default sort order is ascending. Multiple sort criteria are supported.
     */
    public getOrganizationServicesUsingGETWithHttpInfo(orgMrn: string, page?: number, size?: number, sort?: Array<string>, extraHttpRequestParams?: any): Observable<Response> {
        const path = this.basePath + '/oidc/api/org/${orgMrn}/services'
                    .replace('${' + 'orgMrn' + '}', String(orgMrn));

        let queryParameters = new URLSearchParams();
        let headers = new Headers(this.defaultHeaders.toJSON()); // https://github.com/angular/angular/issues/6845
        // verify required parameter 'orgMrn' is not null or undefined
        if (orgMrn === null || orgMrn === undefined) {
            throw new Error('Required parameter orgMrn was null or undefined when calling getOrganizationServicesUsingGET.');
        }
        if (page !== undefined) {
            queryParameters.set('page', <any>page);
        }

        if (size !== undefined) {
            queryParameters.set('size', <any>size);
        }

        if (sort) {
            sort.forEach((element) => {
                queryParameters.append('sort', <any>element);
            })
        }

        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json'
        ];

        // to determine the Accept header
        let produces: string[] = [
            'application/json;charset=UTF-8'
        ];

        let requestOptions: RequestOptionsArgs = new RequestOptions({
            method: RequestMethod.Get,
            headers: headers,
            search: queryParameters,
            withCredentials:this.configuration.withCredentials
        });
        // https://github.com/swagger-api/swagger-codegen/issues/4037
        if (extraHttpRequestParams) {
            requestOptions = (<any>Object).assign(requestOptions, extraHttpRequestParams);
        }

        return this.http.request(path, requestOptions);
    }

    /**
     * getOrganizationServices
     * 
     * @param orgMrn orgMrn
     * @param page Results page you want to retrieve (0..N)
     * @param size Number of records per page
     * @param sort Sorting criteria in the format: property(,asc|desc). Default sort order is ascending. Multiple sort criteria are supported.
     */
    public getOrganizationServicesUsingGET1WithHttpInfo(orgMrn: string, page?: number, size?: number, sort?: Array<string>, extraHttpRequestParams?: any): Observable<Response> {
        const path = this.basePath + '/x509/api/org/${orgMrn}/services'
                    .replace('${' + 'orgMrn' + '}', String(orgMrn));

        let queryParameters = new URLSearchParams();
        let headers = new Headers(this.defaultHeaders.toJSON()); // https://github.com/angular/angular/issues/6845
        // verify required parameter 'orgMrn' is not null or undefined
        if (orgMrn === null || orgMrn === undefined) {
            throw new Error('Required parameter orgMrn was null or undefined when calling getOrganizationServicesUsingGET1.');
        }
        if (page !== undefined) {
            queryParameters.set('page', <any>page);
        }

        if (size !== undefined) {
            queryParameters.set('size', <any>size);
        }

        if (sort) {
            sort.forEach((element) => {
                queryParameters.append('sort', <any>element);
            })
        }

        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json'
        ];

        // to determine the Accept header
        let produces: string[] = [
            'application/json;charset=UTF-8'
        ];

        let requestOptions: RequestOptionsArgs = new RequestOptions({
            method: RequestMethod.Get,
            headers: headers,
            search: queryParameters,
            withCredentials:this.configuration.withCredentials
        });
        // https://github.com/swagger-api/swagger-codegen/issues/4037
        if (extraHttpRequestParams) {
            requestOptions = (<any>Object).assign(requestOptions, extraHttpRequestParams);
        }

        return this.http.request(path, requestOptions);
    }

    /**
     * getServiceJbossXml
     * 
     * @param orgMrn orgMrn
     * @param serviceMrn serviceMrn
     * @param version version
     */
    public getServiceJbossXmlUsingGETWithHttpInfo(orgMrn: string, serviceMrn: string, version: string, extraHttpRequestParams?: any): Observable<Response> {
        const path = this.basePath + '/oidc/api/org/${orgMrn}/service/${serviceMrn}/${version}/jbossxml'
                    .replace('${' + 'orgMrn' + '}', String(orgMrn))
                    .replace('${' + 'serviceMrn' + '}', String(serviceMrn))
                    .replace('${' + 'version' + '}', String(version));

        let queryParameters = new URLSearchParams();
        let headers = new Headers(this.defaultHeaders.toJSON()); // https://github.com/angular/angular/issues/6845
        // verify required parameter 'orgMrn' is not null or undefined
        if (orgMrn === null || orgMrn === undefined) {
            throw new Error('Required parameter orgMrn was null or undefined when calling getServiceJbossXmlUsingGET.');
        }
        // verify required parameter 'serviceMrn' is not null or undefined
        if (serviceMrn === null || serviceMrn === undefined) {
            throw new Error('Required parameter serviceMrn was null or undefined when calling getServiceJbossXmlUsingGET.');
        }
        // verify required parameter 'version' is not null or undefined
        if (version === null || version === undefined) {
            throw new Error('Required parameter version was null or undefined when calling getServiceJbossXmlUsingGET.');
        }
        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json'
        ];

        // to determine the Accept header
        let produces: string[] = [
            '*/*'
        ];

        let requestOptions: RequestOptionsArgs = new RequestOptions({
            method: RequestMethod.Get,
            headers: headers,
            search: queryParameters,
            withCredentials:this.configuration.withCredentials
        });
        // https://github.com/swagger-api/swagger-codegen/issues/4037
        if (extraHttpRequestParams) {
            requestOptions = (<any>Object).assign(requestOptions, extraHttpRequestParams);
        }

        return this.http.request(path, requestOptions);
    }

    /**
     * getServiceJbossXml
     * 
     * @param orgMrn orgMrn
     * @param serviceMrn serviceMrn
     * @param version version
     */
    public getServiceJbossXmlUsingGET1WithHttpInfo(orgMrn: string, serviceMrn: string, version: string, extraHttpRequestParams?: any): Observable<Response> {
        const path = this.basePath + '/x509/api/org/${orgMrn}/service/${serviceMrn}/${version}/jbossxml'
                    .replace('${' + 'orgMrn' + '}', String(orgMrn))
                    .replace('${' + 'serviceMrn' + '}', String(serviceMrn))
                    .replace('${' + 'version' + '}', String(version));

        let queryParameters = new URLSearchParams();
        let headers = new Headers(this.defaultHeaders.toJSON()); // https://github.com/angular/angular/issues/6845
        // verify required parameter 'orgMrn' is not null or undefined
        if (orgMrn === null || orgMrn === undefined) {
            throw new Error('Required parameter orgMrn was null or undefined when calling getServiceJbossXmlUsingGET1.');
        }
        // verify required parameter 'serviceMrn' is not null or undefined
        if (serviceMrn === null || serviceMrn === undefined) {
            throw new Error('Required parameter serviceMrn was null or undefined when calling getServiceJbossXmlUsingGET1.');
        }
        // verify required parameter 'version' is not null or undefined
        if (version === null || version === undefined) {
            throw new Error('Required parameter version was null or undefined when calling getServiceJbossXmlUsingGET1.');
        }
        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json'
        ];

        // to determine the Accept header
        let produces: string[] = [
            '*/*'
        ];

        let requestOptions: RequestOptionsArgs = new RequestOptions({
            method: RequestMethod.Get,
            headers: headers,
            search: queryParameters,
            withCredentials:this.configuration.withCredentials
        });
        // https://github.com/swagger-api/swagger-codegen/issues/4037
        if (extraHttpRequestParams) {
            requestOptions = (<any>Object).assign(requestOptions, extraHttpRequestParams);
        }

        return this.http.request(path, requestOptions);
    }

    /**
     * getServiceKeycloakJson
     * 
     * @param orgMrn orgMrn
     * @param serviceMrn serviceMrn
     * @param version version
     */
    public getServiceKeycloakJsonUsingGETWithHttpInfo(orgMrn: string, serviceMrn: string, version: string, extraHttpRequestParams?: any): Observable<Response> {
        const path = this.basePath + '/oidc/api/org/${orgMrn}/service/${serviceMrn}/${version}/keycloakjson'
                    .replace('${' + 'orgMrn' + '}', String(orgMrn))
                    .replace('${' + 'serviceMrn' + '}', String(serviceMrn))
                    .replace('${' + 'version' + '}', String(version));

        let queryParameters = new URLSearchParams();
        let headers = new Headers(this.defaultHeaders.toJSON()); // https://github.com/angular/angular/issues/6845
        // verify required parameter 'orgMrn' is not null or undefined
        if (orgMrn === null || orgMrn === undefined) {
            throw new Error('Required parameter orgMrn was null or undefined when calling getServiceKeycloakJsonUsingGET.');
        }
        // verify required parameter 'serviceMrn' is not null or undefined
        if (serviceMrn === null || serviceMrn === undefined) {
            throw new Error('Required parameter serviceMrn was null or undefined when calling getServiceKeycloakJsonUsingGET.');
        }
        // verify required parameter 'version' is not null or undefined
        if (version === null || version === undefined) {
            throw new Error('Required parameter version was null or undefined when calling getServiceKeycloakJsonUsingGET.');
        }
        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json'
        ];

        // to determine the Accept header
        let produces: string[] = [
            'application/json;charset=UTF-8'
        ];

        let requestOptions: RequestOptionsArgs = new RequestOptions({
            method: RequestMethod.Get,
            headers: headers,
            search: queryParameters,
            withCredentials:this.configuration.withCredentials
        });
        // https://github.com/swagger-api/swagger-codegen/issues/4037
        if (extraHttpRequestParams) {
            requestOptions = (<any>Object).assign(requestOptions, extraHttpRequestParams);
        }

        return this.http.request(path, requestOptions);
    }

    /**
     * getServiceKeycloakJson
     * 
     * @param orgMrn orgMrn
     * @param serviceMrn serviceMrn
     * @param version version
     */
    public getServiceKeycloakJsonUsingGET1WithHttpInfo(orgMrn: string, serviceMrn: string, version: string, extraHttpRequestParams?: any): Observable<Response> {
        const path = this.basePath + '/x509/api/org/${orgMrn}/service/${serviceMrn}/${version}/keycloakjson'
                    .replace('${' + 'orgMrn' + '}', String(orgMrn))
                    .replace('${' + 'serviceMrn' + '}', String(serviceMrn))
                    .replace('${' + 'version' + '}', String(version));

        let queryParameters = new URLSearchParams();
        let headers = new Headers(this.defaultHeaders.toJSON()); // https://github.com/angular/angular/issues/6845
        // verify required parameter 'orgMrn' is not null or undefined
        if (orgMrn === null || orgMrn === undefined) {
            throw new Error('Required parameter orgMrn was null or undefined when calling getServiceKeycloakJsonUsingGET1.');
        }
        // verify required parameter 'serviceMrn' is not null or undefined
        if (serviceMrn === null || serviceMrn === undefined) {
            throw new Error('Required parameter serviceMrn was null or undefined when calling getServiceKeycloakJsonUsingGET1.');
        }
        // verify required parameter 'version' is not null or undefined
        if (version === null || version === undefined) {
            throw new Error('Required parameter version was null or undefined when calling getServiceKeycloakJsonUsingGET1.');
        }
        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json'
        ];

        // to determine the Accept header
        let produces: string[] = [
            'application/json;charset=UTF-8'
        ];

        let requestOptions: RequestOptionsArgs = new RequestOptions({
            method: RequestMethod.Get,
            headers: headers,
            search: queryParameters,
            withCredentials:this.configuration.withCredentials
        });
        // https://github.com/swagger-api/swagger-codegen/issues/4037
        if (extraHttpRequestParams) {
            requestOptions = (<any>Object).assign(requestOptions, extraHttpRequestParams);
        }

        return this.http.request(path, requestOptions);
    }

    /**
     * getService
     * 
     * @param orgMrn orgMrn
     * @param serviceMrn serviceMrn
     * @param page Results page you want to retrieve (0..N)
     * @param size Number of records per page
     * @param sort Sorting criteria in the format: property(,asc|desc). Default sort order is ascending. Multiple sort criteria are supported.
     */
    public getServiceUsingGETWithHttpInfo(orgMrn: string, serviceMrn: string, page?: number, size?: number, sort?: Array<string>, extraHttpRequestParams?: any): Observable<Response> {
        const path = this.basePath + '/oidc/api/org/${orgMrn}/service/${serviceMrn}'
                    .replace('${' + 'orgMrn' + '}', String(orgMrn))
                    .replace('${' + 'serviceMrn' + '}', String(serviceMrn));

        let queryParameters = new URLSearchParams();
        let headers = new Headers(this.defaultHeaders.toJSON()); // https://github.com/angular/angular/issues/6845
        // verify required parameter 'orgMrn' is not null or undefined
        if (orgMrn === null || orgMrn === undefined) {
            throw new Error('Required parameter orgMrn was null or undefined when calling getServiceUsingGET.');
        }
        // verify required parameter 'serviceMrn' is not null or undefined
        if (serviceMrn === null || serviceMrn === undefined) {
            throw new Error('Required parameter serviceMrn was null or undefined when calling getServiceUsingGET.');
        }
        if (page !== undefined) {
            queryParameters.set('page', <any>page);
        }

        if (size !== undefined) {
            queryParameters.set('size', <any>size);
        }

        if (sort) {
            sort.forEach((element) => {
                queryParameters.append('sort', <any>element);
            })
        }

        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json'
        ];

        // to determine the Accept header
        let produces: string[] = [
            'application/json;charset=UTF-8'
        ];

        let requestOptions: RequestOptionsArgs = new RequestOptions({
            method: RequestMethod.Get,
            headers: headers,
            search: queryParameters,
            withCredentials:this.configuration.withCredentials
        });
        // https://github.com/swagger-api/swagger-codegen/issues/4037
        if (extraHttpRequestParams) {
            requestOptions = (<any>Object).assign(requestOptions, extraHttpRequestParams);
        }

        return this.http.request(path, requestOptions);
    }

    /**
     * getService
     * 
     * @param orgMrn orgMrn
     * @param serviceMrn serviceMrn
     * @param page Results page you want to retrieve (0..N)
     * @param size Number of records per page
     * @param sort Sorting criteria in the format: property(,asc|desc). Default sort order is ascending. Multiple sort criteria are supported.
     */
    public getServiceUsingGET1WithHttpInfo(orgMrn: string, serviceMrn: string, page?: number, size?: number, sort?: Array<string>, extraHttpRequestParams?: any): Observable<Response> {
        const path = this.basePath + '/x509/api/org/${orgMrn}/service/${serviceMrn}'
                    .replace('${' + 'orgMrn' + '}', String(orgMrn))
                    .replace('${' + 'serviceMrn' + '}', String(serviceMrn));

        let queryParameters = new URLSearchParams();
        let headers = new Headers(this.defaultHeaders.toJSON()); // https://github.com/angular/angular/issues/6845
        // verify required parameter 'orgMrn' is not null or undefined
        if (orgMrn === null || orgMrn === undefined) {
            throw new Error('Required parameter orgMrn was null or undefined when calling getServiceUsingGET1.');
        }
        // verify required parameter 'serviceMrn' is not null or undefined
        if (serviceMrn === null || serviceMrn === undefined) {
            throw new Error('Required parameter serviceMrn was null or undefined when calling getServiceUsingGET1.');
        }
        if (page !== undefined) {
            queryParameters.set('page', <any>page);
        }

        if (size !== undefined) {
            queryParameters.set('size', <any>size);
        }

        if (sort) {
            sort.forEach((element) => {
                queryParameters.append('sort', <any>element);
            })
        }

        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json'
        ];

        // to determine the Accept header
        let produces: string[] = [
            'application/json;charset=UTF-8'
        ];

        let requestOptions: RequestOptionsArgs = new RequestOptions({
            method: RequestMethod.Get,
            headers: headers,
            search: queryParameters,
            withCredentials:this.configuration.withCredentials
        });
        // https://github.com/swagger-api/swagger-codegen/issues/4037
        if (extraHttpRequestParams) {
            requestOptions = (<any>Object).assign(requestOptions, extraHttpRequestParams);
        }

        return this.http.request(path, requestOptions);
    }

    /**
     * getServiceVersion
     * 
     * @param orgMrn orgMrn
     * @param serviceMrn serviceMrn
     * @param version version
     */
    public getServiceVersionUsingGETWithHttpInfo(orgMrn: string, serviceMrn: string, version: string, extraHttpRequestParams?: any): Observable<Response> {
        const path = this.basePath + '/oidc/api/org/${orgMrn}/service/${serviceMrn}/${version}'
                    .replace('${' + 'orgMrn' + '}', String(orgMrn))
                    .replace('${' + 'serviceMrn' + '}', String(serviceMrn))
                    .replace('${' + 'version' + '}', String(version));

        let queryParameters = new URLSearchParams();
        let headers = new Headers(this.defaultHeaders.toJSON()); // https://github.com/angular/angular/issues/6845
        // verify required parameter 'orgMrn' is not null or undefined
        if (orgMrn === null || orgMrn === undefined) {
            throw new Error('Required parameter orgMrn was null or undefined when calling getServiceVersionUsingGET.');
        }
        // verify required parameter 'serviceMrn' is not null or undefined
        if (serviceMrn === null || serviceMrn === undefined) {
            throw new Error('Required parameter serviceMrn was null or undefined when calling getServiceVersionUsingGET.');
        }
        // verify required parameter 'version' is not null or undefined
        if (version === null || version === undefined) {
            throw new Error('Required parameter version was null or undefined when calling getServiceVersionUsingGET.');
        }
        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json'
        ];

        // to determine the Accept header
        let produces: string[] = [
            'application/json;charset=UTF-8'
        ];

        let requestOptions: RequestOptionsArgs = new RequestOptions({
            method: RequestMethod.Get,
            headers: headers,
            search: queryParameters,
            withCredentials:this.configuration.withCredentials
        });
        // https://github.com/swagger-api/swagger-codegen/issues/4037
        if (extraHttpRequestParams) {
            requestOptions = (<any>Object).assign(requestOptions, extraHttpRequestParams);
        }

        return this.http.request(path, requestOptions);
    }

    /**
     * getServiceVersion
     * 
     * @param orgMrn orgMrn
     * @param serviceMrn serviceMrn
     * @param version version
     */
    public getServiceVersionUsingGET1WithHttpInfo(orgMrn: string, serviceMrn: string, version: string, extraHttpRequestParams?: any): Observable<Response> {
        const path = this.basePath + '/x509/api/org/${orgMrn}/service/${serviceMrn}/${version}'
                    .replace('${' + 'orgMrn' + '}', String(orgMrn))
                    .replace('${' + 'serviceMrn' + '}', String(serviceMrn))
                    .replace('${' + 'version' + '}', String(version));

        let queryParameters = new URLSearchParams();
        let headers = new Headers(this.defaultHeaders.toJSON()); // https://github.com/angular/angular/issues/6845
        // verify required parameter 'orgMrn' is not null or undefined
        if (orgMrn === null || orgMrn === undefined) {
            throw new Error('Required parameter orgMrn was null or undefined when calling getServiceVersionUsingGET1.');
        }
        // verify required parameter 'serviceMrn' is not null or undefined
        if (serviceMrn === null || serviceMrn === undefined) {
            throw new Error('Required parameter serviceMrn was null or undefined when calling getServiceVersionUsingGET1.');
        }
        // verify required parameter 'version' is not null or undefined
        if (version === null || version === undefined) {
            throw new Error('Required parameter version was null or undefined when calling getServiceVersionUsingGET1.');
        }
        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json'
        ];

        // to determine the Accept header
        let produces: string[] = [
            'application/json;charset=UTF-8'
        ];

        let requestOptions: RequestOptionsArgs = new RequestOptions({
            method: RequestMethod.Get,
            headers: headers,
            search: queryParameters,
            withCredentials:this.configuration.withCredentials
        });
        // https://github.com/swagger-api/swagger-codegen/issues/4037
        if (extraHttpRequestParams) {
            requestOptions = (<any>Object).assign(requestOptions, extraHttpRequestParams);
        }

        return this.http.request(path, requestOptions);
    }

    /**
     * newServiceCert
     * 
     * @param orgMrn orgMrn
     * @param serviceMrn serviceMrn
     * @param version version
     */
    public newServiceCertUsingGETWithHttpInfo(orgMrn: string, serviceMrn: string, version: string, extraHttpRequestParams?: any): Observable<Response> {
        const path = this.basePath + '/oidc/api/org/${orgMrn}/service/${serviceMrn}/${version}/certificate/issue-new'
                    .replace('${' + 'orgMrn' + '}', String(orgMrn))
                    .replace('${' + 'serviceMrn' + '}', String(serviceMrn))
                    .replace('${' + 'version' + '}', String(version));

        let queryParameters = new URLSearchParams();
        let headers = new Headers(this.defaultHeaders.toJSON()); // https://github.com/angular/angular/issues/6845
        // verify required parameter 'orgMrn' is not null or undefined
        if (orgMrn === null || orgMrn === undefined) {
            throw new Error('Required parameter orgMrn was null or undefined when calling newServiceCertUsingGET.');
        }
        // verify required parameter 'serviceMrn' is not null or undefined
        if (serviceMrn === null || serviceMrn === undefined) {
            throw new Error('Required parameter serviceMrn was null or undefined when calling newServiceCertUsingGET.');
        }
        // verify required parameter 'version' is not null or undefined
        if (version === null || version === undefined) {
            throw new Error('Required parameter version was null or undefined when calling newServiceCertUsingGET.');
        }
        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json'
        ];

        // to determine the Accept header
        let produces: string[] = [
            'application/json;charset=UTF-8'
        ];

        let requestOptions: RequestOptionsArgs = new RequestOptions({
            method: RequestMethod.Get,
            headers: headers,
            search: queryParameters,
            withCredentials:this.configuration.withCredentials
        });
        // https://github.com/swagger-api/swagger-codegen/issues/4037
        if (extraHttpRequestParams) {
            requestOptions = (<any>Object).assign(requestOptions, extraHttpRequestParams);
        }

        return this.http.request(path, requestOptions);
    }

    /**
     * newServiceCert
     * 
     * @param orgMrn orgMrn
     * @param serviceMrn serviceMrn
     * @param version version
     */
    public newServiceCertUsingGET1WithHttpInfo(orgMrn: string, serviceMrn: string, version: string, extraHttpRequestParams?: any): Observable<Response> {
        const path = this.basePath + '/x509/api/org/${orgMrn}/service/${serviceMrn}/${version}/certificate/issue-new'
                    .replace('${' + 'orgMrn' + '}', String(orgMrn))
                    .replace('${' + 'serviceMrn' + '}', String(serviceMrn))
                    .replace('${' + 'version' + '}', String(version));

        let queryParameters = new URLSearchParams();
        let headers = new Headers(this.defaultHeaders.toJSON()); // https://github.com/angular/angular/issues/6845
        // verify required parameter 'orgMrn' is not null or undefined
        if (orgMrn === null || orgMrn === undefined) {
            throw new Error('Required parameter orgMrn was null or undefined when calling newServiceCertUsingGET1.');
        }
        // verify required parameter 'serviceMrn' is not null or undefined
        if (serviceMrn === null || serviceMrn === undefined) {
            throw new Error('Required parameter serviceMrn was null or undefined when calling newServiceCertUsingGET1.');
        }
        // verify required parameter 'version' is not null or undefined
        if (version === null || version === undefined) {
            throw new Error('Required parameter version was null or undefined when calling newServiceCertUsingGET1.');
        }
        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json'
        ];

        // to determine the Accept header
        let produces: string[] = [
            'application/json;charset=UTF-8'
        ];

        let requestOptions: RequestOptionsArgs = new RequestOptions({
            method: RequestMethod.Get,
            headers: headers,
            search: queryParameters,
            withCredentials:this.configuration.withCredentials
        });
        // https://github.com/swagger-api/swagger-codegen/issues/4037
        if (extraHttpRequestParams) {
            requestOptions = (<any>Object).assign(requestOptions, extraHttpRequestParams);
        }

        return this.http.request(path, requestOptions);
    }

    /**
     * revokeServiceCert
     * 
     * @param orgMrn orgMrn
     * @param serviceMrn serviceMrn
     * @param version version
     * @param certId certId
     * @param input input
     */
    public revokeServiceCertUsingPOSTWithHttpInfo(orgMrn: string, serviceMrn: string, version: string, certId: string, input: models.CertificateRevocation, extraHttpRequestParams?: any): Observable<Response> {
        const path = this.basePath + '/oidc/api/org/${orgMrn}/service/${serviceMrn}/${version}/certificate/${certId}/revoke'
                    .replace('${' + 'orgMrn' + '}', String(orgMrn))
                    .replace('${' + 'serviceMrn' + '}', String(serviceMrn))
                    .replace('${' + 'version' + '}', String(version))
                    .replace('${' + 'certId' + '}', String(certId));

        let queryParameters = new URLSearchParams();
        let headers = new Headers(this.defaultHeaders.toJSON()); // https://github.com/angular/angular/issues/6845
        // verify required parameter 'orgMrn' is not null or undefined
        if (orgMrn === null || orgMrn === undefined) {
            throw new Error('Required parameter orgMrn was null or undefined when calling revokeServiceCertUsingPOST.');
        }
        // verify required parameter 'serviceMrn' is not null or undefined
        if (serviceMrn === null || serviceMrn === undefined) {
            throw new Error('Required parameter serviceMrn was null or undefined when calling revokeServiceCertUsingPOST.');
        }
        // verify required parameter 'version' is not null or undefined
        if (version === null || version === undefined) {
            throw new Error('Required parameter version was null or undefined when calling revokeServiceCertUsingPOST.');
        }
        // verify required parameter 'certId' is not null or undefined
        if (certId === null || certId === undefined) {
            throw new Error('Required parameter certId was null or undefined when calling revokeServiceCertUsingPOST.');
        }
        // verify required parameter 'input' is not null or undefined
        if (input === null || input === undefined) {
            throw new Error('Required parameter input was null or undefined when calling revokeServiceCertUsingPOST.');
        }
        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json'
        ];

        // to determine the Accept header
        let produces: string[] = [
            'application/json;charset=UTF-8'
        ];

        headers.set('Content-Type', 'application/json');

        let requestOptions: RequestOptionsArgs = new RequestOptions({
            method: RequestMethod.Post,
            headers: headers,
            body: input == null ? '' : JSON.stringify(input), // https://github.com/angular/angular/issues/10612
            search: queryParameters,
            withCredentials:this.configuration.withCredentials
        });
        // https://github.com/swagger-api/swagger-codegen/issues/4037
        if (extraHttpRequestParams) {
            requestOptions = (<any>Object).assign(requestOptions, extraHttpRequestParams);
        }

        return this.http.request(path, requestOptions);
    }

    /**
     * revokeServiceCert
     * 
     * @param orgMrn orgMrn
     * @param serviceMrn serviceMrn
     * @param version version
     * @param certId certId
     * @param input input
     */
    public revokeServiceCertUsingPOST1WithHttpInfo(orgMrn: string, serviceMrn: string, version: string, certId: string, input: models.CertificateRevocation, extraHttpRequestParams?: any): Observable<Response> {
        const path = this.basePath + '/x509/api/org/${orgMrn}/service/${serviceMrn}/${version}/certificate/${certId}/revoke'
                    .replace('${' + 'orgMrn' + '}', String(orgMrn))
                    .replace('${' + 'serviceMrn' + '}', String(serviceMrn))
                    .replace('${' + 'version' + '}', String(version))
                    .replace('${' + 'certId' + '}', String(certId));

        let queryParameters = new URLSearchParams();
        let headers = new Headers(this.defaultHeaders.toJSON()); // https://github.com/angular/angular/issues/6845
        // verify required parameter 'orgMrn' is not null or undefined
        if (orgMrn === null || orgMrn === undefined) {
            throw new Error('Required parameter orgMrn was null or undefined when calling revokeServiceCertUsingPOST1.');
        }
        // verify required parameter 'serviceMrn' is not null or undefined
        if (serviceMrn === null || serviceMrn === undefined) {
            throw new Error('Required parameter serviceMrn was null or undefined when calling revokeServiceCertUsingPOST1.');
        }
        // verify required parameter 'version' is not null or undefined
        if (version === null || version === undefined) {
            throw new Error('Required parameter version was null or undefined when calling revokeServiceCertUsingPOST1.');
        }
        // verify required parameter 'certId' is not null or undefined
        if (certId === null || certId === undefined) {
            throw new Error('Required parameter certId was null or undefined when calling revokeServiceCertUsingPOST1.');
        }
        // verify required parameter 'input' is not null or undefined
        if (input === null || input === undefined) {
            throw new Error('Required parameter input was null or undefined when calling revokeServiceCertUsingPOST1.');
        }
        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json'
        ];

        // to determine the Accept header
        let produces: string[] = [
            'application/json;charset=UTF-8'
        ];

        headers.set('Content-Type', 'application/json');

        let requestOptions: RequestOptionsArgs = new RequestOptions({
            method: RequestMethod.Post,
            headers: headers,
            body: input == null ? '' : JSON.stringify(input), // https://github.com/angular/angular/issues/10612
            search: queryParameters,
            withCredentials:this.configuration.withCredentials
        });
        // https://github.com/swagger-api/swagger-codegen/issues/4037
        if (extraHttpRequestParams) {
            requestOptions = (<any>Object).assign(requestOptions, extraHttpRequestParams);
        }

        return this.http.request(path, requestOptions);
    }

    /**
     * updateService
     * 
     * @param orgMrn orgMrn
     * @param serviceMrn serviceMrn
     * @param version version
     * @param input input
     */
    public updateServiceUsingPUTWithHttpInfo(orgMrn: string, serviceMrn: string, version: string, input: models.Service, extraHttpRequestParams?: any): Observable<Response> {
        const path = this.basePath + '/oidc/api/org/${orgMrn}/service/${serviceMrn}/${version}'
                    .replace('${' + 'orgMrn' + '}', String(orgMrn))
                    .replace('${' + 'serviceMrn' + '}', String(serviceMrn))
                    .replace('${' + 'version' + '}', String(version));

        let queryParameters = new URLSearchParams();
        let headers = new Headers(this.defaultHeaders.toJSON()); // https://github.com/angular/angular/issues/6845
        // verify required parameter 'orgMrn' is not null or undefined
        if (orgMrn === null || orgMrn === undefined) {
            throw new Error('Required parameter orgMrn was null or undefined when calling updateServiceUsingPUT.');
        }
        // verify required parameter 'serviceMrn' is not null or undefined
        if (serviceMrn === null || serviceMrn === undefined) {
            throw new Error('Required parameter serviceMrn was null or undefined when calling updateServiceUsingPUT.');
        }
        // verify required parameter 'version' is not null or undefined
        if (version === null || version === undefined) {
            throw new Error('Required parameter version was null or undefined when calling updateServiceUsingPUT.');
        }
        // verify required parameter 'input' is not null or undefined
        if (input === null || input === undefined) {
            throw new Error('Required parameter input was null or undefined when calling updateServiceUsingPUT.');
        }
        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json'
        ];

        // to determine the Accept header
        let produces: string[] = [
            '*/*'
        ];

        headers.set('Content-Type', 'application/json');

        let requestOptions: RequestOptionsArgs = new RequestOptions({
            method: RequestMethod.Put,
            headers: headers,
            body: input == null ? '' : JSON.stringify(input), // https://github.com/angular/angular/issues/10612
            search: queryParameters,
            withCredentials:this.configuration.withCredentials
        });
        // https://github.com/swagger-api/swagger-codegen/issues/4037
        if (extraHttpRequestParams) {
            requestOptions = (<any>Object).assign(requestOptions, extraHttpRequestParams);
        }

        return this.http.request(path, requestOptions);
    }

    /**
     * updateService
     * 
     * @param orgMrn orgMrn
     * @param serviceMrn serviceMrn
     * @param version version
     * @param input input
     */
    public updateServiceUsingPUT1WithHttpInfo(orgMrn: string, serviceMrn: string, version: string, input: models.Service, extraHttpRequestParams?: any): Observable<Response> {
        const path = this.basePath + '/x509/api/org/${orgMrn}/service/${serviceMrn}/${version}'
                    .replace('${' + 'orgMrn' + '}', String(orgMrn))
                    .replace('${' + 'serviceMrn' + '}', String(serviceMrn))
                    .replace('${' + 'version' + '}', String(version));

        let queryParameters = new URLSearchParams();
        let headers = new Headers(this.defaultHeaders.toJSON()); // https://github.com/angular/angular/issues/6845
        // verify required parameter 'orgMrn' is not null or undefined
        if (orgMrn === null || orgMrn === undefined) {
            throw new Error('Required parameter orgMrn was null or undefined when calling updateServiceUsingPUT1.');
        }
        // verify required parameter 'serviceMrn' is not null or undefined
        if (serviceMrn === null || serviceMrn === undefined) {
            throw new Error('Required parameter serviceMrn was null or undefined when calling updateServiceUsingPUT1.');
        }
        // verify required parameter 'version' is not null or undefined
        if (version === null || version === undefined) {
            throw new Error('Required parameter version was null or undefined when calling updateServiceUsingPUT1.');
        }
        // verify required parameter 'input' is not null or undefined
        if (input === null || input === undefined) {
            throw new Error('Required parameter input was null or undefined when calling updateServiceUsingPUT1.');
        }
        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json'
        ];

        // to determine the Accept header
        let produces: string[] = [
            '*/*'
        ];

        headers.set('Content-Type', 'application/json');

        let requestOptions: RequestOptionsArgs = new RequestOptions({
            method: RequestMethod.Put,
            headers: headers,
            body: input == null ? '' : JSON.stringify(input), // https://github.com/angular/angular/issues/10612
            search: queryParameters,
            withCredentials:this.configuration.withCredentials
        });
        // https://github.com/swagger-api/swagger-codegen/issues/4037
        if (extraHttpRequestParams) {
            requestOptions = (<any>Object).assign(requestOptions, extraHttpRequestParams);
        }

        return this.http.request(path, requestOptions);
    }

}
