/**
 * Maritime Cloud Identity Registry API
 * Maritime Cloud Identity Registry API can be used for managing entities in the Maritime Cloud.
 *
 * OpenAPI spec version: 0.0.1
 * Contact: info@maritimecloud.net
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import {Http, Headers, RequestOptionsArgs, Response, URLSearchParams} from '@angular/http';
import {Injectable, Optional} from '@angular/core';
import {Observable} from 'rxjs/Observable';
import * as models from '../model/models';

/* tslint:disable:no-unused-variable member-ordering */

'use strict';

@Injectable()
export class UsercontrollerApi {
    protected basePath = 'https://api.maritimecloud.net/';
    public defaultHeaders : Headers = new Headers();

    constructor(protected http: Http, @Optional() basePath: string) {
        if (basePath) {
            this.basePath = basePath;
        }
    }

    /**
     * createUser
     * 
     * @param orgMrn orgMrn
     * @param input input
     */
    public createUserUsingPOST (orgMrn: string, input: models.User, extraHttpRequestParams?: any ) : Observable<models.User> {
        const path = this.basePath + '/oidc/api/org/{orgMrn}/user'
            .replace('{' + 'orgMrn' + '}', String(orgMrn));

        let queryParameters = new URLSearchParams();
        let headerParams = this.defaultHeaders;
        // verify required parameter 'orgMrn' is not null or undefined
        if (orgMrn === null || orgMrn === undefined) {
            throw new Error('Required parameter orgMrn was null or undefined when calling createUserUsingPOST.');
        }
        // verify required parameter 'input' is not null or undefined
        if (input === null || input === undefined) {
            throw new Error('Required parameter input was null or undefined when calling createUserUsingPOST.');
        }
        let requestOptions: RequestOptionsArgs = {
            method: 'POST',
            headers: headerParams,
            search: queryParameters
        };
        requestOptions.body = JSON.stringify(input);

        return this.http.request(path, requestOptions)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json();
                }
            });
    }

    /**
     * createUser
     * 
     * @param orgMrn orgMrn
     * @param input input
     */
    public createUserUsingPOST1 (orgMrn: string, input: models.User, extraHttpRequestParams?: any ) : Observable<models.User> {
        const path = this.basePath + '/x509/api/org/{orgMrn}/user'
            .replace('{' + 'orgMrn' + '}', String(orgMrn));

        let queryParameters = new URLSearchParams();
        let headerParams = this.defaultHeaders;
        // verify required parameter 'orgMrn' is not null or undefined
        if (orgMrn === null || orgMrn === undefined) {
            throw new Error('Required parameter orgMrn was null or undefined when calling createUserUsingPOST1.');
        }
        // verify required parameter 'input' is not null or undefined
        if (input === null || input === undefined) {
            throw new Error('Required parameter input was null or undefined when calling createUserUsingPOST1.');
        }
        let requestOptions: RequestOptionsArgs = {
            method: 'POST',
            headers: headerParams,
            search: queryParameters
        };
        requestOptions.body = JSON.stringify(input);

        return this.http.request(path, requestOptions)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json();
                }
            });
    }

    /**
     * deleteUser
     * 
     * @param orgMrn orgMrn
     * @param userMrn userMrn
     */
    public deleteUserUsingDELETE (orgMrn: string, userMrn: string, extraHttpRequestParams?: any ) : Observable<any> {
        const path = this.basePath + '/oidc/api/org/{orgMrn}/user/{userMrn}'
            .replace('{' + 'orgMrn' + '}', String(orgMrn))
            .replace('{' + 'userMrn' + '}', String(userMrn));

        let queryParameters = new URLSearchParams();
        let headerParams = this.defaultHeaders;
        // verify required parameter 'orgMrn' is not null or undefined
        if (orgMrn === null || orgMrn === undefined) {
            throw new Error('Required parameter orgMrn was null or undefined when calling deleteUserUsingDELETE.');
        }
        // verify required parameter 'userMrn' is not null or undefined
        if (userMrn === null || userMrn === undefined) {
            throw new Error('Required parameter userMrn was null or undefined when calling deleteUserUsingDELETE.');
        }
        let requestOptions: RequestOptionsArgs = {
            method: 'DELETE',
            headers: headerParams,
            search: queryParameters
        };

        return this.http.request(path, requestOptions)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json();
                }
            });
    }

    /**
     * deleteUser
     * 
     * @param orgMrn orgMrn
     * @param userMrn userMrn
     */
    public deleteUserUsingDELETE1 (orgMrn: string, userMrn: string, extraHttpRequestParams?: any ) : Observable<any> {
        const path = this.basePath + '/x509/api/org/{orgMrn}/user/{userMrn}'
            .replace('{' + 'orgMrn' + '}', String(orgMrn))
            .replace('{' + 'userMrn' + '}', String(userMrn));

        let queryParameters = new URLSearchParams();
        let headerParams = this.defaultHeaders;
        // verify required parameter 'orgMrn' is not null or undefined
        if (orgMrn === null || orgMrn === undefined) {
            throw new Error('Required parameter orgMrn was null or undefined when calling deleteUserUsingDELETE1.');
        }
        // verify required parameter 'userMrn' is not null or undefined
        if (userMrn === null || userMrn === undefined) {
            throw new Error('Required parameter userMrn was null or undefined when calling deleteUserUsingDELETE1.');
        }
        let requestOptions: RequestOptionsArgs = {
            method: 'DELETE',
            headers: headerParams,
            search: queryParameters
        };

        return this.http.request(path, requestOptions)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json();
                }
            });
    }

    /**
     * getOrganizationUsers
     * 
     * @param orgMrn orgMrn
     */
    public getOrganizationUsersUsingGET (orgMrn: string, extraHttpRequestParams?: any ) : Observable<Array<models.User>> {
        const path = this.basePath + '/oidc/api/org/{orgMrn}/users'
            .replace('{' + 'orgMrn' + '}', String(orgMrn));

        let queryParameters = new URLSearchParams();
        let headerParams = this.defaultHeaders;
        // verify required parameter 'orgMrn' is not null or undefined
        if (orgMrn === null || orgMrn === undefined) {
            throw new Error('Required parameter orgMrn was null or undefined when calling getOrganizationUsersUsingGET.');
        }
        let requestOptions: RequestOptionsArgs = {
            method: 'GET',
            headers: headerParams,
            search: queryParameters
        };

        return this.http.request(path, requestOptions)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json();
                }
            });
    }

    /**
     * getOrganizationUsers
     * 
     * @param orgMrn orgMrn
     */
    public getOrganizationUsersUsingGET1 (orgMrn: string, extraHttpRequestParams?: any ) : Observable<Array<models.User>> {
        const path = this.basePath + '/x509/api/org/{orgMrn}/users'
            .replace('{' + 'orgMrn' + '}', String(orgMrn));

        let queryParameters = new URLSearchParams();
        let headerParams = this.defaultHeaders;
        // verify required parameter 'orgMrn' is not null or undefined
        if (orgMrn === null || orgMrn === undefined) {
            throw new Error('Required parameter orgMrn was null or undefined when calling getOrganizationUsersUsingGET1.');
        }
        let requestOptions: RequestOptionsArgs = {
            method: 'GET',
            headers: headerParams,
            search: queryParameters
        };

        return this.http.request(path, requestOptions)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json();
                }
            });
    }

    /**
     * getUser
     * 
     * @param orgMrn orgMrn
     * @param userMrn userMrn
     */
    public getUserUsingGET (orgMrn: string, userMrn: string, extraHttpRequestParams?: any ) : Observable<models.User> {
        const path = this.basePath + '/oidc/api/org/{orgMrn}/user/{userMrn}'
            .replace('{' + 'orgMrn' + '}', String(orgMrn))
            .replace('{' + 'userMrn' + '}', String(userMrn));

        let queryParameters = new URLSearchParams();
        let headerParams = this.defaultHeaders;
        // verify required parameter 'orgMrn' is not null or undefined
        if (orgMrn === null || orgMrn === undefined) {
            throw new Error('Required parameter orgMrn was null or undefined when calling getUserUsingGET.');
        }
        // verify required parameter 'userMrn' is not null or undefined
        if (userMrn === null || userMrn === undefined) {
            throw new Error('Required parameter userMrn was null or undefined when calling getUserUsingGET.');
        }
        let requestOptions: RequestOptionsArgs = {
            method: 'GET',
            headers: headerParams,
            search: queryParameters
        };

        return this.http.request(path, requestOptions)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json();
                }
            });
    }

    /**
     * getUser
     * 
     * @param orgMrn orgMrn
     * @param userMrn userMrn
     */
    public getUserUsingGET1 (orgMrn: string, userMrn: string, extraHttpRequestParams?: any ) : Observable<models.User> {
        const path = this.basePath + '/x509/api/org/{orgMrn}/user/{userMrn}'
            .replace('{' + 'orgMrn' + '}', String(orgMrn))
            .replace('{' + 'userMrn' + '}', String(userMrn));

        let queryParameters = new URLSearchParams();
        let headerParams = this.defaultHeaders;
        // verify required parameter 'orgMrn' is not null or undefined
        if (orgMrn === null || orgMrn === undefined) {
            throw new Error('Required parameter orgMrn was null or undefined when calling getUserUsingGET1.');
        }
        // verify required parameter 'userMrn' is not null or undefined
        if (userMrn === null || userMrn === undefined) {
            throw new Error('Required parameter userMrn was null or undefined when calling getUserUsingGET1.');
        }
        let requestOptions: RequestOptionsArgs = {
            method: 'GET',
            headers: headerParams,
            search: queryParameters
        };

        return this.http.request(path, requestOptions)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json();
                }
            });
    }

    /**
     * newUserCert
     * 
     * @param orgMrn orgMrn
     * @param userMrn userMrn
     */
    public newUserCertUsingGET (orgMrn: string, userMrn: string, extraHttpRequestParams?: any ) : Observable<models.PemCertificate> {
        const path = this.basePath + '/oidc/api/org/{orgMrn}/user/{userMrn}/certificate/issue-new'
            .replace('{' + 'orgMrn' + '}', String(orgMrn))
            .replace('{' + 'userMrn' + '}', String(userMrn));

        let queryParameters = new URLSearchParams();
        let headerParams = this.defaultHeaders;
        // verify required parameter 'orgMrn' is not null or undefined
        if (orgMrn === null || orgMrn === undefined) {
            throw new Error('Required parameter orgMrn was null or undefined when calling newUserCertUsingGET.');
        }
        // verify required parameter 'userMrn' is not null or undefined
        if (userMrn === null || userMrn === undefined) {
            throw new Error('Required parameter userMrn was null or undefined when calling newUserCertUsingGET.');
        }
        let requestOptions: RequestOptionsArgs = {
            method: 'GET',
            headers: headerParams,
            search: queryParameters
        };

        return this.http.request(path, requestOptions)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json();
                }
            });
    }

    /**
     * newUserCert
     * 
     * @param orgMrn orgMrn
     * @param userMrn userMrn
     */
    public newUserCertUsingGET1 (orgMrn: string, userMrn: string, extraHttpRequestParams?: any ) : Observable<models.PemCertificate> {
        const path = this.basePath + '/x509/api/org/{orgMrn}/user/{userMrn}/certificate/issue-new'
            .replace('{' + 'orgMrn' + '}', String(orgMrn))
            .replace('{' + 'userMrn' + '}', String(userMrn));

        let queryParameters = new URLSearchParams();
        let headerParams = this.defaultHeaders;
        // verify required parameter 'orgMrn' is not null or undefined
        if (orgMrn === null || orgMrn === undefined) {
            throw new Error('Required parameter orgMrn was null or undefined when calling newUserCertUsingGET1.');
        }
        // verify required parameter 'userMrn' is not null or undefined
        if (userMrn === null || userMrn === undefined) {
            throw new Error('Required parameter userMrn was null or undefined when calling newUserCertUsingGET1.');
        }
        let requestOptions: RequestOptionsArgs = {
            method: 'GET',
            headers: headerParams,
            search: queryParameters
        };

        return this.http.request(path, requestOptions)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json();
                }
            });
    }

    /**
     * revokeUserCert
     * 
     * @param orgMrn orgMrn
     * @param userMrn userMrn
     * @param certId certId
     * @param input input
     */
    public revokeUserCertUsingPOST (orgMrn: string, userMrn: string, certId: number, input: models.CertificateRevocation, extraHttpRequestParams?: any ) : Observable<any> {
        const path = this.basePath + '/oidc/api/org/{orgMrn}/user/{userMrn}/certificate/{certId}/revoke'
            .replace('{' + 'orgMrn' + '}', String(orgMrn))
            .replace('{' + 'userMrn' + '}', String(userMrn))
            .replace('{' + 'certId' + '}', String(certId));

        let queryParameters = new URLSearchParams();
        let headerParams = this.defaultHeaders;
        // verify required parameter 'orgMrn' is not null or undefined
        if (orgMrn === null || orgMrn === undefined) {
            throw new Error('Required parameter orgMrn was null or undefined when calling revokeUserCertUsingPOST.');
        }
        // verify required parameter 'userMrn' is not null or undefined
        if (userMrn === null || userMrn === undefined) {
            throw new Error('Required parameter userMrn was null or undefined when calling revokeUserCertUsingPOST.');
        }
        // verify required parameter 'certId' is not null or undefined
        if (certId === null || certId === undefined) {
            throw new Error('Required parameter certId was null or undefined when calling revokeUserCertUsingPOST.');
        }
        // verify required parameter 'input' is not null or undefined
        if (input === null || input === undefined) {
            throw new Error('Required parameter input was null or undefined when calling revokeUserCertUsingPOST.');
        }
        let requestOptions: RequestOptionsArgs = {
            method: 'POST',
            headers: headerParams,
            search: queryParameters
        };
        requestOptions.body = JSON.stringify(input);

        return this.http.request(path, requestOptions)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json();
                }
            });
    }

    /**
     * revokeUserCert
     * 
     * @param orgMrn orgMrn
     * @param userMrn userMrn
     * @param certId certId
     * @param input input
     */
    public revokeUserCertUsingPOST1 (orgMrn: string, userMrn: string, certId: number, input: models.CertificateRevocation, extraHttpRequestParams?: any ) : Observable<any> {
        const path = this.basePath + '/x509/api/org/{orgMrn}/user/{userMrn}/certificate/{certId}/revoke'
            .replace('{' + 'orgMrn' + '}', String(orgMrn))
            .replace('{' + 'userMrn' + '}', String(userMrn))
            .replace('{' + 'certId' + '}', String(certId));

        let queryParameters = new URLSearchParams();
        let headerParams = this.defaultHeaders;
        // verify required parameter 'orgMrn' is not null or undefined
        if (orgMrn === null || orgMrn === undefined) {
            throw new Error('Required parameter orgMrn was null or undefined when calling revokeUserCertUsingPOST1.');
        }
        // verify required parameter 'userMrn' is not null or undefined
        if (userMrn === null || userMrn === undefined) {
            throw new Error('Required parameter userMrn was null or undefined when calling revokeUserCertUsingPOST1.');
        }
        // verify required parameter 'certId' is not null or undefined
        if (certId === null || certId === undefined) {
            throw new Error('Required parameter certId was null or undefined when calling revokeUserCertUsingPOST1.');
        }
        // verify required parameter 'input' is not null or undefined
        if (input === null || input === undefined) {
            throw new Error('Required parameter input was null or undefined when calling revokeUserCertUsingPOST1.');
        }
        let requestOptions: RequestOptionsArgs = {
            method: 'POST',
            headers: headerParams,
            search: queryParameters
        };
        requestOptions.body = JSON.stringify(input);

        return this.http.request(path, requestOptions)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json();
                }
            });
    }

    /**
     * updateUser
     * 
     * @param orgMrn orgMrn
     * @param userMrn userMrn
     * @param input input
     */
    public updateUserUsingPUT (orgMrn: string, userMrn: string, input: models.User, extraHttpRequestParams?: any ) : Observable<any> {
        const path = this.basePath + '/oidc/api/org/{orgMrn}/user/{userMrn}'
            .replace('{' + 'orgMrn' + '}', String(orgMrn))
            .replace('{' + 'userMrn' + '}', String(userMrn));

        let queryParameters = new URLSearchParams();
        let headerParams = this.defaultHeaders;
        // verify required parameter 'orgMrn' is not null or undefined
        if (orgMrn === null || orgMrn === undefined) {
            throw new Error('Required parameter orgMrn was null or undefined when calling updateUserUsingPUT.');
        }
        // verify required parameter 'userMrn' is not null or undefined
        if (userMrn === null || userMrn === undefined) {
            throw new Error('Required parameter userMrn was null or undefined when calling updateUserUsingPUT.');
        }
        // verify required parameter 'input' is not null or undefined
        if (input === null || input === undefined) {
            throw new Error('Required parameter input was null or undefined when calling updateUserUsingPUT.');
        }
        let requestOptions: RequestOptionsArgs = {
            method: 'PUT',
            headers: headerParams,
            search: queryParameters
        };
        requestOptions.body = JSON.stringify(input);

        return this.http.request(path, requestOptions)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json();
                }
            });
    }

    /**
     * updateUser
     * 
     * @param orgMrn orgMrn
     * @param userMrn userMrn
     * @param input input
     */
    public updateUserUsingPUT1 (orgMrn: string, userMrn: string, input: models.User, extraHttpRequestParams?: any ) : Observable<any> {
        const path = this.basePath + '/x509/api/org/{orgMrn}/user/{userMrn}'
            .replace('{' + 'orgMrn' + '}', String(orgMrn))
            .replace('{' + 'userMrn' + '}', String(userMrn));

        let queryParameters = new URLSearchParams();
        let headerParams = this.defaultHeaders;
        // verify required parameter 'orgMrn' is not null or undefined
        if (orgMrn === null || orgMrn === undefined) {
            throw new Error('Required parameter orgMrn was null or undefined when calling updateUserUsingPUT1.');
        }
        // verify required parameter 'userMrn' is not null or undefined
        if (userMrn === null || userMrn === undefined) {
            throw new Error('Required parameter userMrn was null or undefined when calling updateUserUsingPUT1.');
        }
        // verify required parameter 'input' is not null or undefined
        if (input === null || input === undefined) {
            throw new Error('Required parameter input was null or undefined when calling updateUserUsingPUT1.');
        }
        let requestOptions: RequestOptionsArgs = {
            method: 'PUT',
            headers: headerParams,
            search: queryParameters
        };
        requestOptions.body = JSON.stringify(input);

        return this.http.request(path, requestOptions)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json();
                }
            });
    }

}
