/**
 * Maritime Cloud Service Registry API
 * Maritime Cloud Service Registry, developed under the Horizon 2020 Project EfficienSea2, cofunded by the European Union.
 *
 * OpenAPI spec version: 0.7
 * Contact: josef.jahn@frequentis.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

/**
 * Holds a description of a technical design.A design can be compatible to one or morespecification templates.It has at least a technical representation of thedescriptiion in form of an XML and a filled out templateas e.g. word document.
 */
export interface Design {
    comment?: string;

    designAsDoc?: models.Doc;

    designAsXml?: models.Xml;

    designId?: string;

    docs?: Array<models.Doc>;

    id?: number;

    implementedSpecificationVersion?: models.SpecificationTemplate;

    name?: string;

    organizationId?: string;

    specifications?: Array<models.Specification>;

    status?: string;

    version?: string;

    description?: string;

}
