/**
 * mcsr API
 * mcsr API documentation
 *
 * OpenAPI spec version: 0.0.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

'use strict';
import * as models from './models';

/**
 * Holds a description of an service instance.An instance can be compatible to one or morespecification templates.It has at least a technical representation of thedescriptiion in form of an XML and a filled out templateas e.g. word document.
 */
export interface Instance {


    comment?: string;

    designs?: Array<models.Design>;

    docs?: Array<models.Doc>;

    geometry?: Array<string>;

    geometryContentType?: string;

    id?: number;

    implementedSpecificationVersion?: models.SpecificationTemplate;

    instanceAsDoc?: models.Doc;

    instanceAsXml?: models.Xml;

    instanceId?: string;

    keywords?: string;

    name?: string;

    status?: string;

    version?: string;

    description?: string;
}
