/**
 * Maritime Cloud Service Registry API
 * Maritime Cloud Service Registry, developed under the Horizon 2020 Project EfficienSea2, cofunded by the European Union.
 *
 * OpenAPI spec version: 1.0
 * Contact: josef.jahn@frequentis.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

'use strict';
import * as models from './models';

export interface JsonNode {
    

    array?: boolean;

    bigDecimal?: boolean;

    bigInteger?: boolean;

    binary?: boolean;

    boolean?: boolean;

    containerNode?: boolean;

    double?: boolean;

    float?: boolean;

    floatingPointNumber?: boolean;

    int?: boolean;

    integralNumber?: boolean;

    long?: boolean;

    missingNode?: boolean;

    nodeType?: JsonNode.NodeTypeEnum;

    null?: boolean;

    number?: boolean;

    object?: boolean;

    pojo?: boolean;

    short?: boolean;

    textual?: boolean;

    valueNode?: boolean;
}
export namespace JsonNode {

    export enum NodeTypeEnum { 
        ARRAY = <any> 'ARRAY',
        BINARY = <any> 'BINARY',
        BOOLEAN = <any> 'BOOLEAN',
        MISSING = <any> 'MISSING',
        NULL = <any> 'NULL',
        NUMBER = <any> 'NUMBER',
        OBJECT = <any> 'OBJECT',
        POJO = <any> 'POJO',
        STRING = <any> 'STRING',
    }
}
