/**
 * Maritime Cloud Service Registry API
 * Maritime Cloud Service Registry, developed under the Horizon 2020 Project EfficienSea2, cofunded by the European Union.
 *
 * OpenAPI spec version: 1.0
 * Contact: josef.jahn@frequentis.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

/**
 * A SpecificationTemplate contains information on how to define a aspects ofa service.It has a type do differentiate between e.g. logical definitions andconcrete service instances.Templates will evolve, that's why they have a version.
 */
export interface SpecificationTemplate {
    comment?: string;

    docs?: Array<models.Doc>;

    guidelineDoc?: models.Doc;

    id?: number;

    name?: string;

    templateDoc?: models.Doc;

    type?: SpecificationTemplate.TypeEnum;

    version?: string;

    xsds?: Array<models.Xsd>;

}
export namespace SpecificationTemplate {
    export enum TypeEnum {
        SPECIFICATION = <any> 'SPECIFICATION',
        DESIGN = <any> 'DESIGN',
        INSTANCE = <any> 'INSTANCE'
    }
}
